apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: staging-

bases:
- ../../base

configMapGenerator:
- name: the-map
  env: config.properties

images:
- name: monopole/hello
  newTag: "2"

patchesStrategicMerge:
- deployment.yaml
